services:
  limesurvey:
    build: .
    container_name: limesurvey
    restart: always
    ports:
      - "8082:80"
    environment:
      LIMESURVEY_DB_PASSWORD: password
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: FMAT Administrator
      LIMESURVEY_ADMIN_EMAI: lime@lime.lime
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config
      - ./sessions:/var/lime/sessions
      - ./limesurvey-data:/var/www/html/limesurvey
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    container_name: limesurvey-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: limesurvey
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck: # Docker que revise si MySQL está listo antes de permitir que otros servicios dependan de él
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - default
  
  phpmyadmin:
    image: 'phpmyadmin'
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql

volumes:
  mysql:
